Migrate to newfold
newfold-labs/wp-module-secure-passwords pull request #1
Opened 2022-09-26 18:16 UTC by circlecube

## Proposed changes

- Update repo to be in the newfold org with updated links/docs.
- Update to work with newfold module loader
- Update the satis workflow for newfold-labs

## Type of Change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/bluehost/.github/blob/master/.github/contributing.md) doc
- [ ] Linting and tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

2022-09-26 18:34 UTC, wpscholar requested changes
@circlecube  We also need to update the `package.json` file name to be `@newfold-labs/wp-module-secure-passwords`

2022-09-26 18:34 UTC, wpscholar commented on .github/workflows/satis-update.yml
>            event-type: 'Trigger Satis Build'
@circlecube The event type should be changed: 
```suggestion
          event-type: 'satis-build'
```

See https://github.com/newfold-labs/wp-module-coming-soon/blob/trunk/.github/workflows/satis-update.yml#L29

2022-09-26 19:23 UTC, circlecube commented
Got that package.json file updated too, thanks @wpscholar

2022-09-27 01:14 UTC, wpscholar approved these changes

2022-09-27 15:14 UTC, merged